from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd
import json
import os
from typing import List, Dict, Any
from datetime import datetime

app = FastAPI(title="HMS Analytics Microservice")

# CORS Configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, replace with specific Streamlit URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DATA_FILE = os.path.join(os.path.dirname(__file__), 'mock_data.json')

def load_data():
    if not os.path.exists(DATA_FILE):
        # Attempt to generate data if missing (mostly for local dev)
        try:
            from .faker_data import generate_data
            generate_data()
        except ImportError:
            # Fallback if running from root
            from backend.faker_data import generate_data
            generate_data()
            
    with open(DATA_FILE, 'r') as f:
        return json.load(f)

@app.get("/api/v1/analytics/doctor-patient-insights")
def get_insights():
    try:
        raw_data = load_data()
        
        # Convert to DataFrames
        df_doctors = pd.DataFrame(raw_data['doctors'])
        df_patients = pd.DataFrame(raw_data['patients'])
        df_visits = pd.DataFrame(raw_data['case_history'])
        df_prescriptions = pd.DataFrame(raw_data['prescriptions'])
        
        # Merge for easier analysis
        df_visits_docs = df_visits.merge(df_doctors, on='doctor_id', how='left')
        df_visits_patients = df_visits.merge(df_patients, on='patient_id', how='left')
        
        insights = []
        
        # --- 1. Doctor Performance ---
        
        # Insight 1: Top 5 Busiest Doctors
        top_docs = df_visits_docs['name'].value_counts().head(5)
        insights.append({
            "title": "Top 5 Busiest Doctors",
            "description": "Doctors with the highest patient volume.",
            "chart_type": "bar",
            "chart_data": {"labels": top_docs.index.tolist(), "values": top_docs.values.tolist()}
        })
        
        # Insight 2: Visits by Department
        dept_counts = df_visits_docs['department'].value_counts()
        insights.append({
            "title": "Patient Visits by Department",
            "description": "Distribution of cases across different medical departments.",
            "chart_type": "pie",
            "chart_data": {"labels": dept_counts.index.tolist(), "values": dept_counts.values.tolist()}
        })
        
        # Insight 3: Revenue per Department
        rev_dept = df_visits_docs.groupby('department')['consultation_fee'].sum().sort_values(ascending=False)
        insights.append({
            "title": "Revenue by Department",
            "description": "Total consultation fees generated by each department.",
            "chart_type": "bar",
            "chart_data": {"labels": rev_dept.index.tolist(), "values": rev_dept.values.tolist()}
        })
        
        # Insight 4: Average Consultation Fee per Doctor
        avg_fee_doc = df_visits_docs.groupby('name')['consultation_fee'].mean().sort_values(ascending=False).head(10)
        insights.append({
            "title": "Top 10 Doctors by Avg Consultation Fee",
            "description": "Doctors with the highest average consultation charges.",
            "chart_type": "bar",
            "chart_data": {"labels": avg_fee_doc.index.tolist(), "values": avg_fee_doc.values.tolist()}
        })
        
        # --- 2. Patient Demographics ---
        
        # Insight 5: Patient Age Distribution
        # Binning ages
        age_bins = [0, 18, 30, 50, 70, 100]
        age_labels = ['0-18', '19-30', '31-50', '51-70', '70+']
        df_patients['age_group'] = pd.cut(df_patients['age'], bins=age_bins, labels=age_labels)
        age_dist = df_patients['age_group'].value_counts().sort_index()
        insights.append({
            "title": "Patient Age Group Distribution",
            "description": "Demographic breakdown of patients by age groups.",
            "chart_type": "bar",
            "chart_data": {"labels": age_dist.index.tolist(), "values": age_dist.values.tolist()}
        })
        
        # Insight 6: Gender Distribution
        gender_dist = df_patients['gender'].value_counts()
        insights.append({
            "title": "Patient Gender Distribution",
            "description": "Split between Male and Female patients.",
            "chart_type": "pie",
            "chart_data": {"labels": gender_dist.index.tolist(), "values": gender_dist.values.tolist()}
        })
        
        # Insight 7: Top 10 Patient Cities
        city_dist = df_patients['city'].value_counts().head(10)
        insights.append({
            "title": "Top 10 Patient Locations",
            "description": "Cities with the highest number of registered patients.",
            "chart_type": "bar",
            "chart_data": {"labels": city_dist.index.tolist(), "values": city_dist.values.tolist()}
        })
        
        # --- 3. Clinical Demand ---
        
        # Insight 8: OPD vs Emergency
        visit_type_dist = df_visits['visit_type'].value_counts()
        insights.append({
            "title": "OPD vs Emergency Visits",
            "description": "Ratio of routine OPD visits to Emergency cases.",
            "chart_type": "pie",
            "chart_data": {"labels": visit_type_dist.index.tolist(), "values": visit_type_dist.values.tolist()}
        })
        
        # Insight 9: Top 10 Prescribed Medicines
        med_counts = df_prescriptions['medicine_name'].value_counts().head(10)
        insights.append({
            "title": "Top 10 Prescribed Medicines",
            "description": "Most frequently prescribed drugs.",
            "chart_type": "bar",
            "chart_data": {"labels": med_counts.index.tolist(), "values": med_counts.values.tolist()}
        })
        
        # Insight 10: Monthly Visit Trends
        df_visits['visit_date'] = pd.to_datetime(df_visits['visit_date'])
        monthly_visits = df_visits.set_index('visit_date').resample('M').size()
        # Format dates as strings
        monthly_labels = monthly_visits.index.strftime('%Y-%m').tolist()
        insights.append({
            "title": "Monthly Patient Visits Trend",
            "description": "Trend of patient visits over time.",
            "chart_type": "line",
            "chart_data": {"labels": monthly_labels, "values": monthly_visits.values.tolist()}
        })
        
        # Insight 11: Busiest Days of the Week
        df_visits['day_of_week'] = df_visits['visit_date'].dt.day_name()
        # Order days
        days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        day_counts = df_visits['day_of_week'].value_counts().reindex(days_order)
        insights.append({
            "title": "Visits by Day of Week",
            "description": "Patient volume distribution across the week.",
            "chart_type": "bar",
            "chart_data": {"labels": day_counts.index.tolist(), "values": day_counts.values.tolist()}
        })
        
        # Insight 12: Top 5 Diagnoses
        diag_counts = df_visits['diagnosis'].value_counts().head(5)
        insights.append({
            "title": "Top 5 Common Diagnoses",
            "description": "Most frequent medical diagnoses recorded.",
            "chart_type": "bar",
            "chart_data": {"labels": diag_counts.index.tolist(), "values": diag_counts.values.tolist()}
        })
        
        # Insight 13: Average Medicines per Prescription
        # Group prescriptions by case_id
        meds_per_case = df_prescriptions.groupby('case_id').size()
        # Distribution of count
        med_count_dist = meds_per_case.value_counts().sort_index()
        insights.append({
            "title": "Medicines per Prescription Distribution",
            "description": "How many medicines are typically prescribed in a single visit.",
            "chart_type": "bar",
            "chart_data": {"labels": [str(x) for x in med_count_dist.index.tolist()], "values": med_count_dist.values.tolist()}
        })
        
        # Insight 14: Emergency Cases by Department
        # Filter for Emergency
        emergency_visits = df_visits_docs[df_visits_docs['visit_type'] == 'Emergency']
        emerg_dept = emergency_visits['department'].value_counts()
        insights.append({
            "title": "Emergency Cases by Department",
            "description": "Which departments handle the most emergency cases.",
            "chart_type": "bar",
            "chart_data": {"labels": emerg_dept.index.tolist(), "values": emerg_dept.values.tolist()}
        })
        
        # Insight 15: Patient Retention (Repeat Visits)
        visit_counts = df_visits['patient_id'].value_counts()
        repeat_patients = visit_counts[visit_counts > 1].count()
        single_visit_patients = visit_counts[visit_counts == 1].count()
        insights.append({
            "title": "Patient Retention Rate",
            "description": "Proportion of patients with repeat visits vs single visits.",
            "chart_type": "pie",
            "chart_data": {"labels": ["Repeat Patients", "One-time Patients"], "values": [int(repeat_patients), int(single_visit_patients)]}
        })

        # Insight 16: Visits by Hour of Day
        df_visits['hour'] = df_visits['visit_date'].dt.hour
        hour_counts = df_visits['hour'].value_counts().sort_index()
        insights.append({
            "title": "Peak Visiting Hours",
            "description": "Patient traffic throughout the day.",
            "chart_type": "line",
            "chart_data": {"labels": [f"{h}:00" for h in hour_counts.index.tolist()], "values": hour_counts.values.tolist()}
        })

        # Insight 17: Average Age by Department
        # Merge visits with patients and doctors
        df_full = df_visits.merge(df_patients, on='patient_id').merge(df_doctors, on='doctor_id', suffixes=('_patient', '_doctor'))
        avg_age_dept = df_full.groupby('department')['age'].mean().sort_values()
        insights.append({
            "title": "Average Patient Age by Department",
            "description": "Average age of patients visiting each department.",
            "chart_type": "bar",
            "chart_data": {"labels": avg_age_dept.index.tolist(), "values": avg_age_dept.values.tolist()}
        })

        # Insight 18: Gender Split in Emergency
        emerg_gender = df_full[df_full['visit_type'] == 'Emergency']['gender'].value_counts()
        insights.append({
            "title": "Gender Distribution in Emergency",
            "description": "Gender breakdown for emergency visits.",
            "chart_type": "pie",
            "chart_data": {"labels": emerg_gender.index.tolist(), "values": emerg_gender.values.tolist()}
        })

        # Insight 19: Top 5 Doctors for Pediatrics
        # Note: Doctor name is now name_doctor due to suffix
        peds_docs = df_full[df_full['department'] == 'Pediatrics']['name_doctor'].value_counts().head(5)
        insights.append({
            "title": "Top 5 Pediatricians",
            "description": "Busiest doctors in the Pediatrics department.",
            "chart_type": "bar",
            "chart_data": {"labels": peds_docs.index.tolist(), "values": peds_docs.values.tolist()}
        })

        # Insight 20: Total Revenue Over Time
        monthly_rev = df_visits.set_index('visit_date').resample('M')['consultation_fee'].sum()
        insights.append({
            "title": "Monthly Revenue Trend",
            "description": "Total consultation fees collected over time.",
            "chart_type": "line",
            "chart_data": {"labels": monthly_rev.index.strftime('%Y-%m').tolist(), "values": monthly_rev.values.tolist()}
        })
        
        return insights

    except Exception as e:
        import traceback
        traceback.print_exc()
        # detailed error message
        error_msg = str(e)
        if 'df_visits_docs' in locals():
            error_msg += f" | df_visits_docs cols: {df_visits_docs.columns.tolist()}"
        if 'df_doctors' in locals():
            error_msg += f" | df_doctors cols: {df_doctors.columns.tolist()}"
        print(error_msg)
        raise HTTPException(status_code=500, detail=error_msg)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
